sudo: false # use newer travis infrastructure
language: ruby
before_script:
  - mysql -e 'create database ranked_model_test;'
  - psql -c 'create database ranked_model_test;' -U postgres
rvm:
  - "2.1.8"
  - "2.2.4"
  - "2.3.0"
  - "jruby-19mode"
env:
  - "ACTIVERECORD_VERSION=4.2.7"
  - "ACTIVERECORD_VERSION=4.2.7 DB=mysql_travis"
  - "ACTIVERECORD_VERSION=4.2.7 DB=postgresql_travis"
  - "ACTIVERECORD_VERSION=5.0.1"
  - "ACTIVERECORD_VERSION=5.0.1 DB=mysql_travis"
  - "ACTIVERECORD_VERSION=5.0.1 DB=postgresql_travis"
  - "ACTIVERECORD_VERSION=master"
  - "ACTIVERECORD_VERSION=master DB=mysql_travis"
  - "ACTIVERECORD_VERSION=master DB=postgresql_travis"
matrix:
  exclude:
    - env: "ACTIVERECORD_VERSION=5.0.1"
      rvm: "2.1.8"
    - env: "ACTIVERECORD_VERSION=5.0.1 DB=mysql_travis"
      rvm: "2.1.8"
    - env: "ACTIVERECORD_VERSION=5.0.1 DB=postgresql_travis"
      rvm: "2.1.8"
    - env: "ACTIVERECORD_VERSION=5.0.1"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=5.0.1 DB=mysql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=5.0.1 DB=postgresql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=master"
      rvm: "2.1.8"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
      rvm: "2.1.8"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
      rvm: "2.1.8"
    - env: "ACTIVERECORD_VERSION=master"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
      rvm: "jruby-19mode"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
      rvm: "jruby-19mode"
  allow_failures:
    # Master may or may not pass
    - env: "ACTIVERECORD_VERSION=master"
    - env: "ACTIVERECORD_VERSION=master DB=mysql_travis"
    - env: "ACTIVERECORD_VERSION=master DB=postgresql_travis"
